5-Ruby-on-Rails/config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  get 'logout', to: 'sessions#destroy'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  resources :users, only: %i[new create]
  resources :articles
end

5-Ruby-on-Rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

5-Ruby-on-Rails/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true
end

5-Ruby-on-Rails/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :articles, dependent: :delete_all

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i

  validates :name, presence: true
  validates :surname, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def full_name
    "#{name} #{surname}"
  end
end

5-Ruby-on-Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

5-Ruby-on-Rails/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper

  before_action :set_article, only: %i[show edit update destroy]
  before_action :article_exists?, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit update destroy]
  before_action :is_logged_in?, only: %i[new create]

  def index
    @selected_user = User.find_by_id(params[:user_id])
    @selected_sort = params[:sort]
    @articles = requested_articles
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully deleted.'
  end

  private

  def set_article
    @article = Article.find_by(id: params[:id])
  end

  def is_logged_in?
    redirect_to root_path, alert: 'You must log in to create an article' unless logged_in?
  end

  def article_exists?
    redirect_to root_path, alert: 'The requested article does not exist' unless @article.present?
  end

  def correct_user
    redirect_to root_path, alert: 'You can only edit or delete your own articles.' unless @article.user == current_user
  end

  def article_params
    params.require(:article).permit(:title, :content).merge({ user: current_user })
  end
end

5-Ruby-on-Rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user&.authenticate(params[:password])
      log_in user
      redirect_to root_url, notice: "Logged in as #{user.name} #{user.surname}!"
    else
      flash.now[:alert] = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url, notice: 'Logged out!'
  end
end

5-Ruby-on-Rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation)
  end
end

5-Ruby-on-Rails/app/helpers/application_helper.rb
module ApplicationHelper
end

5-Ruby-on-Rails/app/helpers/articles_helper.rb
module ArticlesHelper
  def requested_articles
    articles = @selected_user&.articles || Article.all

    articles.order selected_sort_option
  end

  def selected_sort_option
    case @selected_sort&.to_sym
    when :created_desc
      { created_at: :desc }
    when :created_asc
      { created_at: :asc }
    when :updated_desc
      { updated_at: :desc }
    when :updated_asc
      { updated_at: :asc }
    else
      { created_at: :desc }
    end
  end

  def sorting_options
    [
        ['Created: newest', :created_desc],
        ['Created: oldest', :created_asc],
        ['Updated: newest', :updated_desc],
        ['Updated: oldest', :updated_asc]
    ]
  end

  def no_articles_message
    if @selected_user.present?
      "No articles from #{@selected_user.full_name} yet."
    else
      'No articles to display yet.'
    end
  end
end

5-Ruby-on-Rails/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session[:user_id] = nil
  end

  def logged_in?
    session[:user_id].present?
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

5-Ruby-on-Rails/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'new-article-content' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

5-Ruby-on-Rails/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show article', @article, data: { confirm: 'All unsaved changes will be lost, are you sure?' }, class: 'button-link' %>

5-Ruby-on-Rails/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Articles list</h1>
<section class="actions">
  <p>Sort by:</p>
  <%= select_tag "author",
                 options_for_select(sorting_options, @selected_sort),
                 id: 'select-sorting' %>
  <p>Author:</p>
  <%= select_tag "author",
                 options_from_collection_for_select(User.all, 'id', 'full_name', @selected_user&.id),
                 include_blank: 'All',
                 id: 'select-author' %>
</section>

<section class="actions">
  <%= link_to 'New Article', new_article_path, class: %w[button-link flex-end] %>
</section>

<br>

<section class="large">
  <% if @articles.any? %>
    <% @articles.each do |article| %>
      <%= render 'layouts/article_preview', article: article %>
    <% end %>
  <% else %>
    <h3><%= no_articles_message %></h3>
  <% end %>
</section>

5-Ruby-on-Rails/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

5-Ruby-on-Rails/app/views/articles/show.html.erb
<p id="notice" class="centered"><%= notice %></p>

<%= render 'layouts/article', article: @article %>

5-Ruby-on-Rails/app/views/layouts/_article.html.erb
<h1>Article detail</h1>
<br>
<section class="article large">
  <h1 class="title centered"><%= article.title %></h1>
  <p class="content"><%= article.content %></p>
  <div class="author">Author: <%= article.user.full_name %></div>
  <% if current_user == article.user %>
    <div class="actions">
      <%= link_to 'Edit', edit_article_path(article), class: 'button-link' %>
      <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button-link' %>
    </div>
  <% end %>
</section>

5-Ruby-on-Rails/app/views/layouts/_article_preview.html.erb
<div class="article-preview">
  <h2 class="title"><%= article.title %></h2>
  <h4 class="author">Author: <strong><%= "#{article.user.full_name}" %></strong></h4>
  <div class="created-at flex-end">Created: <strong><%= article.created_at.strftime("%F") %></strong></div>
  <div class="updated-at flex-end">Last modified at: <strong><%= article.updated_at.strftime("%F") %></strong></div>
  <div class="show flex-end">
    <%= link_to 'Read', article, class: 'button-link' %>
  </div>
</div>

5-Ruby-on-Rails/app/views/layouts/_header.html.erb
<section class="header">
  <%= link_to 'Home', root_path %>

  <div class="flex-end">
    <% if logged_in? %>
      Logged in as <%= "#{current_user.name} #{current_user.surname}" %>
      <%= link_to 'Logout', logout_path %>
    <% else %>
      <%= link_to 'Login', login_path %>
      <%= link_to 'Signup', new_user_path %>
    <% end %>
  </div>
</section>

5-Ruby-on-Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="centered">
      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

5-Ruby-on-Rails/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

5-Ruby-on-Rails/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user %>